name: 'Unity - Test runner'
author: Webber Takken <webber@takken.io>
description: 'Run tests for any Unity project.'
inputs:
  unityVersion:
    required: false
    default: 'auto'
    description: 'Version of unity to use for testing the project. Use "auto" to get from your ProjectSettings/ProjectVersion.txt'
  customImage:
    required: false
    default: ''
    description: 'Specific docker image that should be used for testing the project'
  projectPath:
    required: false
    description: 'Path to the Unity project to be tested.'
  testMode:
    required: false
    default: 'all'
    description: 'The type of tests to be run by the test runner.'
  artifactsPath:
    required: false
    default: 'artifacts'
    description: 'Path where test artifacts should be stored.'
  useNetworkHost:
    required: false
    default: 'false'
    description: 'Initialises Docker using the hosts network.'
  enableCodeCoverage:
    required: false
    default: 'false'
    description: 'Enables code coverage and allows access to the Coverage API.'
  coverageOptions:
    required: false
    default: ''
    description: 'Set extra options to pass to Coverage API. Available options are enableCyclomaticComplexity;generateHtmlReport;generateBadgeReport;assemblyFilters.'
  coverageResultsPath:
    required: false
    default: 'artifacts'
    description: 'Path where coverage results should be stored.'
  coverageOnly:
    required: false
    default: 'false'
    description: 'Run only coverage (no tests), useful to merge already generated coverages together.'
  debugCodeOptimization:
    required: false
    default: 'false'
    description: 'Code Optimization was introduced in 2020.1. Code Optimization mode defines whether Unity Editor compiles scripts in Debug or Release mode. Debug mode enables C# debugging and it is required in order to obtain accurate code coverage.'
  customParameters:
    required: false
    description: 'Extra parameters to configure the Unity editor run.'
outputs:
  artifactsPath:
    description: 'Path where the artifacts are stored'
branding:
  icon: 'box'
  color: 'gray-dark'
runs:
  using: 'node12'
  main: 'action/index.js'
